---
title: "SCI_scraping_invert_data_cleaning_IM"
output: html_document
date: "2023-07-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##Clear R's memory to start with clean slate
rm(list = ls())

##Import libraries
library(tidyverse)
library(stringr)
library(readxl)
library(here)
library(janitor)
library(vegan)


##Set working directory and import data
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```


# clean and separate 2009-2014 raw count and measured data into => count_data and size_data
```{r}
#for invert scrapping biomass data
## i messed up my personal working directory so a work around is that 
#split <- read_excel("data/SCI_Resource_Data_2009_2014_raw.xlsx", sheet ="Split", na=c("","."))
#rough <- read_excel("data/SCI_Resource_Data_2009_2014_raw.xlsx", sheet = "Rough", na=c("","."," "))

split <- read_xlsx(file.choose("SCI_Resource_Data_2009_2014_raw.xlsx"), sheet ="Split", na=c("","."))
rough <- read_xlsx(file.choose("SCI_Resource_Data_2009_2014_raw.xlsx"), sheet ="Rough", na=c("","."))

split1 <-split %>%
  dplyr::select(-Sorter) %>%
  mutate(Site=ifelse(Site=="Twin W","Twin West",Site)) %>%
  mutate_if(is.numeric, ~replace_na(., 0))%>%
  pivot_longer(cols=`Gammarid_<0.5`:Sponge, names_to="spe",values_to ="measurement") %>% #not really length, just the value from the cell which is number in this case
  mutate(source="Split") 

rough1 <-rough %>%
  dplyr::select(-Sorter) %>%
  mutate(Site=ifelse(Site=="Twin W","Twin West",Site)) %>%
  mutate_if(is.numeric, ~replace_na(., 0)) %>%
  pivot_longer(cols=`Pachy_0.0-9.9`:Sponge, names_to="spe",values_to ="measurement") %>%
  mutate(source="Rough")
  
all <- bind_rows(split1,rough1)

all1 <- all %>%
  separate(spe, into = c("TAXA", "size"), sep="_(?=[^_]+$)")%>%
  mutate(count = str_extract(TAXA, "[0-9]*$"), TAXA = gsub('[0-9]+', '', TAXA), TAXA=trimws(TAXA)) %>%
  mutate(year=substr(as.character(Date),1,4)) %>%
  mutate(day=substr(as.character(Date),9,10)) %>% 
  mutate(month=substr(as.character(Date),6,7)) %>% 
  rename_with(toupper) %>%
  dplyr::select(YEAR, MONTH, DAY, DATE, SITE, DEPTH, REP, TAXA, SIZE, MEASUREMENT, COUNT, FRACTION, SOURCE) #this line basically removed the measurements of the inverts and only kept the general size classes
  
all1 <-clean_names(all1)
all1$site <- tolower(all1$site)
all1$taxa <- tolower(all1$taxa)
all1$source <- tolower(all1$source)

#clean up naming inconsistencies 
all1 <- all1 %>% 
  mutate(taxa=ifelse(taxa== "poly.", "polychaete", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "gastro", "gastropod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "gastro.", "gastropod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "brittle stars", "brittle star", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "caprellids", "caprellid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "unknown isopod", "isopod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "isopods", "isopod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "jaeropsids", "isopod", taxa)) %>% #wasnt there to begin with?
  mutate(taxa=ifelse(taxa== "jaerop", "isopod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "sea star", "starfish", taxa)) %>% #undo this
  mutate(taxa=ifelse(taxa== "chaet", "polychaete", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "fish larv.", "fish", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "mysids", "mysid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "crab larvae", "crabs", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "urchins", "urchin", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "gammarids", "gammarid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "bivalves", "bivalve", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "anenome", "anemone", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "sea anem", "anemone", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "crust", "crusta", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "crusta", "crustacean", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "amphipoda", "amphipod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "crabs count", "crabs number", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "urchin count", "urchins number", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "opistob", "opisthob", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "opisthob", "heterobranch", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "tube worm", "polychaete", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "unid worm", "polychaete", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "cuke", "sea cucumber", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "crab larvae", "crabs", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "sphaerm", "sphaeromatid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "crabs", "crab", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "copepods", "copepod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "ostracods", "ostracod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "unidentified", "unknown", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "coleortera", "coleoptera", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "crabs number", "crab", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "urchins number", "urchin", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "srs number", "srs", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "lrs number", "lrs", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "isopods number", "isopod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "gammarids number", "gammarid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "isopods", "isopod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "ostracods", "ostracod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "tanaids", "tanaid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "sea cucumber", "cucumaria", taxa)) 
  

  
# separating the counts from the measure values so that they are in different columns
# we saw that in all 1 there were many counts mixed with length measurement, because the split/rough were so messy
# size measure species and exclude the species name that's the same as one of the 6. exclude these 6 but keep the one that has "number"

measured_taxa_rough <- c("crab",	"urchin", "srs", "lrs", "isopod", "gammarid")
measured_taxa_split <- c("crab", "urchin")

#all the count data, need to rename measurement column
#need to figure out issue with "number" taxa: crabs #, srs #, urchins #, lrs #, isopods #, gammarids #
count_dt <- all1 %>% 
  filter(!((taxa %in% measured_taxa_rough & source=="rough")|(taxa %in% measured_taxa_split & source=="split"))) 

size_dt <- all1 %>% 
  filter((taxa %in% measured_taxa_rough & source=="rough")|(taxa %in% measured_taxa_split & source=="split"))

#clean up size_dt first: 
# 1. delete size column 2.rename measurement to size 3. delete count column
size_dt <- subset(size_dt, select = -size)
size_dt <-subset(size_dt, select = -count)
colnames(size_dt)[9] = "size"

#clean up count_dt:
#1. delete count column 2. rename measurement to count 
count_dt <- subset(count_dt, select= -count)
colnames(count_dt)[10] = "count"

#count column is irrelevant and the measurement is the organism count 
#double check older dataset
#rename measurement to size, then merge with older 
```


# clean 1982-2008 count data
```{r}
count_1982_2008 <- read_csv(here("data", "SCI_Scrapes_Counted_Invertebrates_1982-2009.csv"))

count_1982_2008 <- count_1982_2008 %>% 
   mutate(SITE=ifelse(SITE=="Twin W","Twin West", SITE)) %>% 
   mutate(TAXA = gsub('[].[]', ' ', TAXA), TAXA=trimws(TAXA)) %>% 
   mutate_if(is.numeric, ~replace_na(., 0)) %>% 
   mutate(month=substr(as.character(DATE),6,7)) %>%
   mutate(day=substr(as.character(DATE),9,10)) %>% 
   rename_with(toupper) %>%
   dplyr::select(YEAR,MONTH,DAY,DATE,SITE,DEPTH,REP,TAXA,SIZE_CLASS_MG,COUNT,FRACTION_SORTED,SOURCE) %>% 
   rename(size = SIZE_CLASS_MG)

count_1982_2008 <- clean_names(count_1982_2008)
count_1982_2008$site <- tolower(count_1982_2008$site)
count_1982_2008$taxa <- tolower(count_1982_2008$taxa)
count_1982_2008$source <- tolower(count_1982_2008$source)

#removing 2009 from this data set because it was less complete than in the 2009-2014 file
count_1982_2008 <- subset(count_1982_2008, year != 2009)
colnames(count_1982_2008)[11] = "fraction"

count_1982_2008 <- count_1982_2008 %>% 
  mutate(taxa=ifelse(taxa== "amphipoda", "amphipod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "unidentified amphipod", "amphipod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "anthuroid isopod", "anthuroid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "bivalves", "bivalve", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "brittle stars", "brittle star", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "caprellids", "caprellid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "chaet", "polychaete", taxa)) %>%
  mutate(taxa=ifelse(taxa== "poly", "polychaete", taxa)) %>%
  mutate(taxa=ifelse(taxa== "unidentified worm", "polychaete", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "unidentifiedworm", "polychaete", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "tanaids", "tanaid", taxa)) %>%
  mutate(taxa=ifelse(taxa== "opistob", "opisthob", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "opisthob", "heterobranch", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "mysids", "mysid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "cirolanid isopod", "cirolanid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "copepods", "copepod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "crust", "crusta", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "crusta", "crustacean", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "gastro", "gastropod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "gastropods", "gastropod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "idoteaids", "idoteid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "idoteid", "idotea", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "sea anem", "anemone", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "anenome", "anemone", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "unidentified isopod", "isopod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "crab larvae", "crab", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "cuke", "cucumaria", taxa)) %>% 
  mutate(site=ifelse(site== "frys i", "frys 1", site)) %>% 
  mutate(site=ifelse(site== "twin e", "twin east", site)) %>% 
  mutate(taxa=ifelse(taxa== "sea star", "starfish", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "unidentified", "unknown", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "ostracods", "ostracod", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "cyphonautes", "electra", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "tube worm", "polychaete", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "coleortera", "coleoptera", taxa)) 
```

# clean 1982-2008 size data 
```{r}
measure_1982_2008 <- read_csv(here("data", "SCI_Scrapes_Measured_Invertebrates_1982-2009.csv"))

measure_1982_2008 <- measure_1982_2008 %>% 
   mutate(SITE=ifelse(SITE=="Twin W","Twin West", SITE)) %>% 
   mutate_if(is.numeric, ~replace_na(., 0)) %>% 
   mutate(month=substr(as.character(DATE),6,7)) %>%
   mutate(day=substr(as.character(DATE),9,10)) %>% 
   rename_with(toupper) %>%
   select(YEAR,MONTH,DAY,DATE,SITE,DEPTH,REP,TAXA,SIZE,COUNT,FRACTION_SORTED,SOURCE)

measure_1982_2008 <- clean_names(measure_1982_2008)
measure_1982_2008$site <- tolower(measure_1982_2008$site)
measure_1982_2008$taxa <- tolower(measure_1982_2008$taxa)
measure_1982_2008$source <- tolower(measure_1982_2008$source)

measure_1982_2008 <- measure_1982_2008 %>% 
  mutate(site=ifelse(site== "frys i", "frys 1", site)) %>% 
  mutate(site=ifelse(site== "twin e", "twin east", site)) %>% 
  mutate(taxa=ifelse(taxa== "crabs", "crab", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "gammarids", "gammarid", taxa)) %>% 
  mutate(taxa=ifelse(taxa== "isopods", "isopod", taxa))

colnames(measure_1982_2008)[11] = "fraction"

#removing 2009 from this data set because it was less complete than in the 2009-2014 file
measure_1982_2008 <- subset(measure_1982_2008, year != 2009)
```

# combine and export all count data years 1982-2014
## final tweaks
```{r}
count_dt <- count_dt %>% 
  mutate(year=as.numeric(year))

count_1982_2008 <- count_1982_2008 %>% 
  mutate(depth=as.numeric(depth)) %>% 
  mutate(rep=as.numeric(rep)) 

count_all <- bind_rows(count_dt, count_1982_2008)
  
count_all <- count_all[!(count_all$taxa %in% "unknown"),]

write.csv(count_all,"../SCI_count_data_1982-2014.csv")

invertnamesall <- unique(count_all$taxa)

write.csv(invertnamesall, "/Users/inezmangino/Desktop/santa cruz lter/invertnamesall.csv", row.names=FALSE)
```

# combine and export all size data years 1982-2014
```{r}
size_dt <- size_dt %>% 
  mutate(year=as.numeric(year))

measure_1982_2008 <- measure_1982_2008 %>% 
  mutate(depth=as.numeric(depth)) %>% 
  mutate(rep=as.numeric(rep))

size_all <-bind_rows(size_dt, measure_1982_2008) 

unique(size_all$taxa)

# dropping 0's from this dataframe
size_all[size_all == 0] <- NA
size_all_no_zeros <- na.omit(size_all)

write.csv(size_all,"../SCI_size_data_1982-2014.csv")
```
```{r}
size_all_prey <- size_all_no_zeros %>% 
  filter(site %in% prey_density_sites)

size_all_prey_continuous_dates <- size_all_prey %>% 
  filter(year %in% continuous_years)

size_all_cleaned <- size_all_prey_continuous_dates %>% 
  filter(month %in% oct_nov)
```

```{r}
write.csv(size_all_cleaned,"../invert_size_cleaned_years_prey_density_sites.csv",row.names = F,quote = T,na="-99999")
```

```{r}
prey_density_sites <- c("bc 1", "diablo", "twin west")

continuous_years <- c("1995", "1996","1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014")

oct_nov <- c("10", "11")

count_all[count_all == 0] <- NA
count_all_no_zeros <- na.omit(count_all)

count_all_prey <- count_all_no_zeros %>% 
  filter(site %in% prey_density_sites)

count_all_prey_continuous_dates <- count_all_prey %>% 
  filter(year %in% continuous_years)

count_all_cleaned <- count_all_prey_continuous_dates %>% 
  filter(month %in% oct_nov)

count
```

```{r}
write.csv(count_all_cleaned,"../invert_counts_cleaned_years_prey_density_sites.csv",row.names = F,quote = T,na="-99999")
```

#checking frequencies
```{r}
pow <- size_all_no_zeros %>%
  distinct(date,site,depth,rep)%>%
  group_by(date,site)%>%
  summarise(freq=n())

pow2 <- size_all_no_zeros %>% 
  distinct(year, month, depth, rep) %>% 
  group_by(month) %>% 
  summarise(freq=n())

pow3 <- size_all %>% 
  distinct(year, month, date, depth, rep) %>% 
  group_by(month) %>% 
  summarise(freq=n())
```

