---
title: "algae_and_invert_explore_2"
output: html_document
date: "2023-11-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Loading libraries
```{r}
library(tidyverse)
library(dplyr)
library(stringr)
library(readxl)
library(here)
library(janitor)
library(vegan)
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(forcats)
library(lme4)
library(glmmTMB)
library(corrplot)
library(biostat3)
library(explore)
library(performance)
library(see)
library(patchwork)
library(car)
library(plotrix)
library(conflicted)
library(reshape2)
library(iNEXT)
```

#Uploading and prepping dataframes for analysis
```{r}
algae <- read_csv(here("data", "algae_weight_cleaned_years_prey_density_sites.csv"))
invert_count <- read_csv(here("data", "count_all3_cleaned_12082023.csv"))
invert_size <- read_csv(here("data", "size_all_cleaned_11282023.csv"))

invert_count <- invert_count[,-1]

invert_count <- invert_count %>% 
  filter(taxa !="cyprid") %>% 
  filter(fraction!= "0.083333333") %>% 
  mutate(multiplier = case_when(fraction == "1"~1, fraction == "0.75"~4, fraction == "0.625"~8, 
                                fraction == "0.5"~2, fraction =="0.25"~4, fraction == "0.125"~8,  
                                fraction == "0.0625"~16, fraction == "0.03125"~32, 
                                fraction == "0.015625"~64, fraction == "0.0078125"~128, 
                                fraction == "0.00390625"~256, fraction == "0.001953125"~512)) %>%
  mutate(count = case_when(count == -199998~0, TRUE~count)) %>% 
  mutate(count = case_when(count == -99999~0, TRUE~count)) %>% 
  mutate(count = case_when(is.na(count)~0, TRUE~count)) %>% 
  mutate(scaled_count = count * multiplier) %>% 
  mutate(PA= case_when(scaled_count >= 1~1, scaled_count == 0~0)) 
```

#Algae calculations 
```{r}
#calculating biomass and assigning a presence & absence count of each alga individual
algae <- algae %>% 
  mutate(area_m2= 0.1) %>% 
  mutate(biomass_gm2 = wet_wt * 10) %>% 
  mutate(PA= case_when(biomass_gm2 >= 1~1, biomass_gm2 == 0~0)) 

#matrix with algae biomass and columns on the end with algae community metrics
algae_matrix_biomass <- algae %>% 
  filter(sp_code !="red") %>% 
  filter(sp_code !="green") %>%
  filter(sp_code !="fau") %>% 
  select(year, month, date, site, depth, rep, sp_code, biomass_gm2) %>% 
  pivot_wider(names_from = sp_code, values_from = biomass_gm2)

#algae matrix with 1 or 0 coded into the cell, used to create a richness measure
algae_matrix_richness <- algae %>% 
  filter(sp_code !="red") %>% 
  filter(sp_code !="green") %>% 
  filter(sp_code !="fau") %>% 
  select(year, month, date, site, depth, rep, sp_code, PA) %>% 
  pivot_wider(names_from = sp_code, values_from = PA)

#algae matrix with 1 or 0 coded into the cell, and then a column on the end summing the total species count
algae_matrix_richness_2 <- algae_matrix_richness %>% 
  group_by(year, month, date, site, depth, rep) %>% 
  mutate(sum_count = sum(art,	cho,	clad,	cod,	colp,	dic,	egr,	eis,	gel,	gn,	gr,	gym,	lam,	laur,	ploc,	pri, rho,	stos))

#creating a dataframe combining biomass and richness metrics so I can calculate diversity
biomass_PA <- merge(algae_matrix_biomass, algae_matrix_richness, by= c('year', 'month', 'date', 'site', 'depth', 'rep'))

#algae matrix with biomass and all other temporal and spatial data removed
algae_matrix_biomass_2 <- algae_matrix_biomass[-c(1:6)]

#biodiversity metrics
algae_matrix_biomass$richness <- apply(algae_matrix_biomass[,7:24], 1, function(i) sum(i>0))
algae_matrix_biomass$shannon <- diversity(algae_matrix_biomass_2, index = 'shannon') 
algae_matrix_biomass$simpson <- diversity(algae_matrix_biomass_2, index = 'simpson') 
algae_matrix_biomass$invsimpson <- diversity(algae_matrix_biomass_2, index = 'invsimpson') 
algae_matrix_biomass <- algae_matrix_biomass %>% 
  mutate(div_order1= exp(shannon))
#add a column for every row that sums the algae biomass
algae_matrix_biomass$sum_algae_biomass <- rowSums(algae_matrix_biomass[,7:24])
#add a column for every row that identifies the dominant algae species for values greater than zero
algae_matrix_biomass$dominant_algae <- apply(algae_matrix_biomass[,7:24], 1, function(i) names(i)[i==max(i)])

#calculate which species of algae were the top 10 most dominant (in terms of biomass) over the entire time series
dominant_algae_species <- algae_matrix_biomass %>% 
  summarise(across(art:stos, sum)) %>% 
  pivot_longer(cols = art:stos, names_to = "species", values_to = "biomass") %>% 
  arrange(desc(biomass)) %>% 
  filter(biomass > 0) %>% 
  mutate(species = fct_reorder(species, biomass)) %>% 
  mutate(species = fct_rev(species)) %>% 
  mutate(species = fct_relevel(species, "art", "gr", "rho", "cod", "colp", "eis", "stos", "dic", "laur", "ploc"))
dominant_algae_species <- dominant_algae_species[-c(11:16),]
```

#Algae plots
```{r}
algae_hill1 <- algae_matrix_biomass %>% 
  group_by(year) %>% 
  summarise(mean_hill = mean(div_order1), sd_hill = sd(div_order1))

ggplot(algae_hill1, aes(x=year, y=mean_hill)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=mean_hill-sd_hill, ymax=mean_hill+sd_hill), width=.1) +
  labs(title="Mean Hill Diversity Over Time", x="Year", y="Mean Hill Diversity") +
  theme(plot.title = element_text(hjust = 0.5))
```

#EDA: algae
```{r}
#Histogram
ggplot(algae, aes(x = wet_wt)) +
  geom_histogram()

smaller <- algae |> 
  filter(wet_wt < 10)

ggplot(smaller, aes(x = wet_wt)) +
  geom_histogram()

#Box plot
boxplot(algae$wet_wt~algae$sp_code)

#QQ-plot
ggplot(data = algae, aes(sample = wet_wt)) +
  geom_qq() + theme_bw()

#Density plot overlay on histogram
ggplot(data= algae, aes(x= wet_wt)) +                                
  geom_histogram(bins = 30) +
  geom_density(col = "red", size=2)
```

#Invert calculations
```{r}
#replace placeholder count values with 0
invert_scaled <- subset(invert_count, select = -c(fraction,source,count,multiplier))
invert_scaled <- invert_scaled[, c(1,2,3,4,5,6,7,8,21,20,9,10,11,12,13,14,15,16,17,18)]
 
#family PA matrix
invert_family_matrix_PA <- invert_scaled %>% 
  filter(family !="NA") %>%
  select(year, month, date, site, depth, rep, family, PA) %>% 
  pivot_wider(names_from = family, values_from = PA, values_fn = list(PA= sum)) %>% 
  mutate(across(everything(), ~replace_na(., 0))) 

#family richness matrix
invert_scaled_family <- invert_scaled %>% 
  group_by(year, month, date, site, depth, rep, family) %>% 
  summarise(scaled_count = sum(scaled_count))

invert_scaled_family2 <- invert_scaled_family %>% 
  filter(family !="NA") %>%
  group_by(year) %>%
  summarise(scaled_count = sum(scaled_count)) %>% 
  unique()
  
invert_scaled_family2 <- subset(invert_scaled_family, select = -c(month,date,site,depth,rep))

invert_family_matrix_richness <- invert_scaled_family %>% 
  select(year, month, date, site, depth, rep, family, scaled_count) %>% 
  pivot_wider(names_from = family, values_from = scaled_count) %>% 
  mutate(across(everything(), ~replace_na(., 0))) %>% 
  select(-c("NA"))

#creating a dataframe combining biomass and richness metrics so I can calculate diversity
richness_PA <- merge(invert_family_matrix_richness, invert_family_matrix_PA, by= c('year', 'month', 'date', 'site', 'depth', 'rep'))
invert_family_matrix_richness_2 <- invert_family_matrix_richness[-c(1:6)]

#calculating biodiversity metrics
invert_family_matrix_richness$richness <- apply(invert_family_matrix_richness[,7:21], 1, function(i) sum(i>0))
invert_family_matrix_richness$shannon <- diversity(invert_family_matrix_richness_2, index = 'shannon') #typically 0.5 to 2
invert_family_matrix_richness$simpson <- diversity(invert_family_matrix_richness_2, index = 'simpson')
invert_family_matrix_richness$invsimpson <- diversity(invert_family_matrix_richness_2, index = 'invsimpson')
invert_family_matrix_richness <- invert_family_matrix_richness %>% 
  mutate(div_order1= exp(shannon))

#matrix by order
invert_scaled_order <- invert_scaled %>% 
  group_by(year, month, date, site, depth, rep, order) %>% 
  summarise(scaled_count = sum(scaled_count))

invert_matrix_order <- invert_scaled_order %>% 
  select(year, month, date, site, depth, rep, order, scaled_count) %>% 
  pivot_wider(names_from = order, values_from = scaled_count) %>% 
  mutate(across(everything(), ~replace_na(., 0))) %>% 
  select(-c("NA"))

invert_family_test <- invert_scaled_family %>% 
  group_by(family) %>%
  summarise(scaled_count = sum(scaled_count)) 

invert_order_test <- invert_scaled_order %>% 
  group_by(order) %>%
  summarise(scaled_count = sum(scaled_count)) 
```

#1/17/2023 updates
```{r}
#create a master dataframe combining algae biomass and invert counts
invert_algae <- merge(invert_family_matrix_richness, algae_matrix_biomass, by= c('year', 'month', 'date', 'site', 'depth', 'rep'))

invert_algae %>% 
  mutate(dominant_algae = apply(algae_matrix_biomass[,7:24], 1, function(i) names(i)[i==max(i)]))



```
